Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.define :web do |c|
    c.vm.hostname = 'web.com'
    c.vm.network 'private_network', ip: '192.168.30.10'
    c.vm.provider :virtualbox do |vbox|
      vbox.customize ['modifyvm', :id, '--memory', 512]
      vbox.customize ['modifyvm', :id, '--cpus', 1]
    end
  end
end
