SOURCE_HTMLS = Dir.glob('template/*.html')
SOURCE_HTMLS.delete('template/header_menu.html')

output_htmls = []

def make_html(source_html_name, output_html_name)
  source_html = File.read(source_html_name, encoding: 'utf-8')
  menu_html = File.read('template/header_menu.html', encoding: 'utf-8')

  open(output_html_name, 'w') do |f|
    f.write source_html.gsub('{HEADER_MENU_HTML}', menu_html)
  end

  $stderr.puts "#{source_html_name} ---> #{output_html_name}"
end

# rakeタスク
task :default => :publish

SOURCE_HTMLS.each do |source_html_name|
  output_html_name = source_html_name.sub(/^template\//, '')
  output_htmls << output_html_name

  desc "#{output_html_name}を作成する"
  file output_html_name => [source_html_name, 'template/header_menu.html'] do
    make_html(source_html_name, output_html_name)
  end
end

desc '全HTMLファイルを作成する'
task :publish => output_htmls
